### ISSUE TITLE
Add Sphinx requirements

### ISSUE THREAD

**Issue by Jeffrey-Lim** [TeamEpochGithub/epochalyst#48]
The Sphinx documentation requirements are not listed anywhere. The requirements are not in the `requirements.txt` and we probably don't want to have them there either, since you don't want to install those just to run `epochalyst`. We might want to list them in `docs/requirements.txt` or something instead with this content:

```
sphinx~=7.2.6
sphinx-autodoc-typehints~=2.0.0
sphinxawesome-theme~=5.1.1
myst-parser~=2.0.0
pygit2~=1.14.1
```

Or we could migrate this project to use Poetry instead and add the Sphinx requirements as an optional dependency group:

```toml
[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-autodoc-typehints = "^2.0.0"
sphinxawesome-theme = "^5.1.1"
myst-parser = "^2.0.0"
pygit2 = "^1.14.1"
```

Another related issue is that Sphinx autosummary seems to be unable to import private classes/functions, so a lot of modules are missing. See #47.
